<template >
  <loading v-model:active="isLoading" :can-cancel="true" :is-full-page="true">
    <div class="loadingio-spinner-ripple-ljxkgz2dr4f">
      <div class="ldio-b6pegcgibx6">
        <div></div>
        <div></div>
      </div>
    </div>
  </loading>
  <router-view></router-view>
</template>
<script>
import { mapMutations } from "vuex";
import Loading from "vue-loading-overlay";
import axios from "axios";
import "vue-loading-overlay/dist/vue-loading.css";
export default {
  name: "App",
  components: {
    Loading,
  },
  computed: {
    isLoading() {
      return this.$store.state.isLoading;
    },
  },
  created() {
    this.initialize();
    window.addEventListener("resize", this.detectWindowWidth);
    this.$nextTick(() => {
      // 獲得目前位置
      if (navigator.geolocation) {
        console.log("初始化座標");
        navigator.geolocation.getCurrentPosition((position) => {
          const p = position.coords;
          // 將獲取的經緯度轉換成縣市
          axios
            .get(
              `https://api.nlsc.gov.tw/other/TownVillagePointQuery/${p.longitude}/${p.latitude}/4326/`
            )
            .then((response) => {
              const ctyName = response.data.ctyName;
              console.log(ctyName);
              this.$store.commit("setLocation", ctyName);
              // 將中心點設為目前的位置
              this.$store.commit("setMapCenter", [p.latitude, p.longitude]);
              this.$store.commit("setGps", [p.latitude, p.longitude]);
            })
            .catch((error) => console.log(error));
        });
      }
    });
    if (this.$route.path == "/") {
      this.$router.push("/searchBus");
    }
  },
  destroyed() {
    window.removeEventListener("resize", this.detectWindowWidth);
  },
  mounted() {},
  methods: {
    ...mapMutations(["setWindowWidth"]),
    initialize() {
      this.detectWindowWidth();
    },
    detectWindowWidth() {
      this.setWindowWidth(window.innerWidth);
    },
  },
};
</script>

<style lang="scss" scoped>
@keyframes ldio-b6pegcgibx6 {
  0% {
    top: 88px;
    left: 88px;
    width: 0;
    height: 0;
    opacity: 1;
  }
  100% {
    top: 14px;
    left: 14px;
    width: 148px;
    height: 148px;
    opacity: 0;
  }
}
.ldio-b6pegcgibx6 div {
  position: absolute;
  border-width: 12px;
  border-style: solid;
  opacity: 1;
  border-radius: 50%;
  animation: ldio-b6pegcgibx6 1s cubic-bezier(0, 0.2, 0.8, 1) infinite;
}
.ldio-b6pegcgibx6 div:nth-child(1) {
  border-color: #e50914;
  animation-delay: 0s;
}
.ldio-b6pegcgibx6 div:nth-child(2) {
  border-color: #221f1f;
  animation-delay: -0.5s;
}
.loadingio-spinner-ripple-ljxkgz2dr4f {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
}
.ldio-b6pegcgibx6 {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-b6pegcgibx6 div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>